# Generated by Django 3.2.22 on 2023-11-03 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sound_manager', '0002_auto_20231102_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soundfile',
            options={'managed': False},
        ),
    ]
